import { useEffect, useState } from 'react'
import PortalLayout from '../components/PortalLayout'
import { useAuth } from '../lib/AuthContext'
import { supabase } from '../lib/supabaseClient'

const TABS = ['Documents', 'Users', 'Messages']
const askTwice = (first, second) => window.confirm(first) && window.confirm(second)

export default function AdminDashboard() {
  const { user } = useAuth()
  const [tab, setTab] = useState('Documents')
  return <PortalLayout><h1 className="mb-1 text-3xl font-display">Admin Dashboard</h1><p className="mb-6 text-sm text-slate">Manage documents, users, and portal messages.</p><div className="mb-6 flex gap-1 border-b border-slate/20">{TABS.map((item) => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-4 py-2.5 text-sm font-medium transition-colors ${tab === item ? 'border-rust text-rust' : 'border-transparent text-slate hover:text-ink'}`}>{item}</button>)}</div>{tab === 'Documents' && <DocumentsPanel />}{tab === 'Users' && <UsersPanel currentUserId={user?.id} />}{tab === 'Messages' && <MessagesPanel />}</PortalLayout>
}

function Notice({ error, success }) { return <>{error && <p className="mb-4 text-sm text-rust" role="alert">{error}</p>}{success && <p className="mb-4 text-sm text-green-700" role="status">{success}</p>}</> }

function DocumentsPanel() {
  const [docs, setDocs] = useState([]), [title, setTitle] = useState(''), [category, setCategory] = useState('General'), [file, setFile] = useState(null), [editing, setEditing] = useState(null), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false)
  const load = async () => { const { data, error: loadError } = await supabase.from('documents').select('id,title,category,file_path,created_at').order('created_at', { ascending: false }); setDocs(data || []); if (loadError) setError(loadError.message) }
  useEffect(() => { load() }, [])
  async function save(event) { event.preventDefault(); setBusy(true); setError(''); setSuccess(''); if (editing) { const { error: updateError } = await supabase.from('documents').update({ title, category }).eq('id', editing.id); if (updateError) setError(updateError.message); else { setSuccess('Document updated.'); setEditing(null); setTitle(''); setCategory('General'); await load() } } else { if (!file) { setError('Please choose a file.'); setBusy(false); return } const filePath = `${Date.now()}_${file.name}`; const { error: uploadError } = await supabase.storage.from('documents').upload(filePath, file); if (uploadError) setError(uploadError.message); else { const { error: insertError } = await supabase.from('documents').insert({ title: title || file.name, category, file_path: filePath }); if (insertError) { await supabase.storage.from('documents').remove([filePath]); setError(insertError.message) } else { setSuccess('Document uploaded.'); setTitle(''); setCategory('General'); setFile(null); await load() } } } setBusy(false) }
  async function remove(doc) { if (!askTwice(`Delete “${doc.title}”? This cannot be undone.`, 'Final confirmation: permanently delete this document?')) return; setError(''); const { error: storageError } = await supabase.storage.from('documents').remove([doc.file_path]); const { error: dbError } = await supabase.from('documents').delete().eq('id', doc.id); if (storageError || dbError) setError(storageError?.message || dbError?.message); else { setSuccess('Document deleted.'); await load() } }
  return <div className="grid gap-8 lg:grid-cols-3"><form onSubmit={save} className="h-fit space-y-4 border border-slate/20 bg-white/40 p-5"><h2 className="font-display text-xl">{editing ? 'Edit Document' : 'Upload Document'}</h2><Notice error={error} success={success} /><label className="block text-sm">Title<input value={title} onChange={(e) => setTitle(e.target.value)} className="mt-1 w-full border border-slate/40 bg-transparent px-3 py-2" /></label><label className="block text-sm">Category<select value={category} onChange={(e) => setCategory(e.target.value)} className="mt-1 w-full border border-slate/40 bg-transparent px-3 py-2">{['General','Certificate','License','Contract','Report'].map((x) => <option key={x}>{x}</option>)}</select></label>{!editing && <label className="block text-sm">File<input type="file" required onChange={(e) => setFile(e.target.files?.[0] || null)} className="mt-1 w-full text-sm" /></label>}<button disabled={busy} className="w-full bg-rust py-2.5 text-sand disabled:opacity-60">{busy ? 'Saving…' : editing ? 'Save Changes' : 'Upload'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setTitle(''); setCategory('General') }} className="w-full border border-slate/40 py-2">Cancel</button>}</form><div className="lg:col-span-2"><h2 className="mb-4 font-display text-xl">All Documents</h2><div className="divide-y divide-slate/20 border border-slate/20 bg-white/40">{docs.map((doc) => <div key={doc.id} className="flex items-center justify-between gap-3 p-4"><div><strong>{doc.title}</strong><p className="text-xs text-slate">{doc.category}</p></div><div className="flex gap-2"><button onClick={() => { setEditing(doc); setTitle(doc.title); setCategory(doc.category) }} className="border border-slate/40 px-3 py-1.5 text-sm">Edit</button><button onClick={() => remove(doc)} className="border border-red-300 px-3 py-1.5 text-sm text-red-700">Delete</button></div></div>)}{!docs.length && <p className="p-5 text-slate">No documents yet.</p>}</div></div></div>
}

function UsersPanel({ currentUserId }) {
  const [users, setUsers] = useState([]), [form, setForm] = useState({ fullName: '', email: '', password: '', role: 'user' }), [editing, setEditing] = useState(null), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false)
  const load = async () => { const { data, error: loadError } = await supabase.from('profiles').select('id,full_name,role,created_at').order('created_at'); setUsers(data || []); if (loadError) setError(loadError.message) }
  useEffect(() => { load() }, [])
  async function manage(body) { const { data: { session } } = await supabase.auth.getSession(); if (!session?.access_token) throw new Error('Your session has expired. Please sign in again.'); const { data, error: functionError } = await supabase.functions.invoke('admin-create-user', { body, headers: { Authorization: `Bearer ${session.access_token}` } }); if (functionError) throw new Error(/Failed to send a request/i.test(functionError.message) ? 'User management service is unavailable. Confirm the Edge Function is deployed.' : functionError.message); if (data?.error) throw new Error(data.error); return data }
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { if (editing) { const { error: updateError } = await supabase.from('profiles').update({ full_name: form.fullName }).eq('id', editing.id); if (updateError) throw updateError; setSuccess('User name updated.'); setEditing(null) } else { const result = await manage({ action: 'create', email: form.email, password: form.password, full_name: form.fullName, role: form.role }); setSuccess(result.message || 'Account created.') } setForm({ fullName: '', email: '', password: '', role: 'user' }); await load() } catch (err) { setError(err.message) } setBusy(false) }
  async function changeRole(item) { const next = item.role === 'admin' ? 'user' : 'admin'; if (item.role === 'admin' && users.filter((u) => u.role === 'admin').length === 1) { setError('At least one Admin user must remain in the system.'); return } if (!askTwice(`Change ${item.full_name} from ${item.role.toUpperCase()} to ${next.toUpperCase()}?`, 'Security confirmation required. Confirm this role change.')) return; try { const result = await manage({ action: 'change_role', user_id: item.id, role: next }); setSuccess(result.message || 'Role updated.'); await load() } catch (err) { setError(err.message) } }
  async function remove(item) { if (item.id === currentUserId) { setError('You cannot delete your own account.'); return } if (item.role === 'admin' && users.filter((u) => u.role === 'admin').length === 1) { setError('At least one Admin user must remain in the system.'); return } if (!askTwice(`Delete ${item.full_name}? The account can be recreated later.`, 'Final confirmation: permanently delete this user?')) return; try { const result = await manage({ action: 'delete', user_id: item.id }); setSuccess(result.message || 'User deleted.'); await load() } catch (err) { setError(err.message) } }
  return <div className="grid gap-8 lg:grid-cols-3"><form onSubmit={submit} className="h-fit space-y-4 border border-slate/20 bg-white/40 p-5"><h2 className="font-display text-xl">{editing ? 'Edit User' : 'Create Account'}</h2><Notice error={error} success={success} /><label className="block text-sm">Full name<input required value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} className="mt-1 w-full border border-slate/40 bg-transparent px-3 py-2" /></label>{!editing && <><label className="block text-sm">Email<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-1 w-full border border-slate/40 bg-transparent px-3 py-2" /></label><label className="block text-sm">Temporary password<input type="password" minLength={8} required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="mt-1 w-full border border-slate/40 bg-transparent px-3 py-2" /></label><label className="block text-sm">Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="mt-1 w-full border border-slate/40 bg-transparent px-3 py-2"><option value="user">Normal User</option><option value="admin">Admin</option></select></label></>}<button disabled={busy} className="w-full bg-rust py-2.5 text-sand disabled:opacity-60">{busy ? 'Saving…' : editing ? 'Save User' : 'Create Account'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm({ fullName: '', email: '', password: '', role: 'user' }) }} className="w-full border border-slate/40 py-2">Cancel</button>}</form><div className="lg:col-span-2"><h2 className="mb-4 font-display text-xl">Portal Users</h2><div className="divide-y divide-slate/20 border border-slate/20 bg-white/40">{users.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 p-4"><div><strong>{item.full_name}</strong><p className="text-xs uppercase text-slate">{item.role}</p></div><div className="flex flex-wrap justify-end gap-2"><button onClick={() => { setEditing(item); setForm({ fullName: item.full_name, email: '', password: '', role: item.role }) }} className="border border-slate/40 px-3 py-1.5 text-sm">Edit</button><button onClick={() => changeRole(item)} className="border border-slate/40 px-3 py-1.5 text-sm">Change Role</button><button onClick={() => remove(item)} className="border border-red-300 px-3 py-1.5 text-sm text-red-700">Delete</button></div></div>)}</div></div></div>
}

function MessagesPanel() {
  const [messages, setMessages] = useState([]), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const load = async () => { const { data, error: loadError } = await supabase.from('portal_messages').select('id,subject,message,priority,is_read,archived_at,created_at,sender:profiles!sender_id(full_name)').is('archived_at', null).order('created_at', { ascending: false }); setMessages(data || []); if (loadError) setError(loadError.message) }
  useEffect(() => { load() }, [])
  async function update(item, changes) { const { error: updateError } = await supabase.from('portal_messages').update(changes).eq('id', item.id); if (updateError) setError(updateError.message); else { setSuccess('Message updated.'); await load() } }
  async function remove(item) { if (!askTwice(`Delete “${item.subject}”? This cannot be undone.`, 'Final confirmation: permanently delete this message?')) return; const { error: deleteError } = await supabase.from('portal_messages').delete().eq('id', item.id); if (deleteError) setError(deleteError.message); else { setSuccess('Message deleted.'); await load() } }
  return <div><Notice error={error} success={success} /><h2 className="mb-4 font-display text-xl">Portal Messages</h2><div className="divide-y divide-slate/20 border border-slate/20 bg-white/40">{messages.map((item) => <div key={item.id} className="p-5"><div className="flex justify-between gap-3"><strong>{item.subject}</strong><span className="text-xs text-slate">{new Date(item.created_at).toLocaleString()}</span></div><p className="text-xs text-slate">From: {item.sender?.full_name || 'Unknown'} · {item.priority}</p><p className="my-3 text-sm">{item.message}</p><div className="flex gap-2"><button onClick={() => update(item, { is_read: true })} className="border border-slate/40 px-3 py-1.5 text-sm">Mark Read</button><button onClick={() => update(item, { archived_at: new Date().toISOString() })} className="border border-slate/40 px-3 py-1.5 text-sm">Archive</button><button onClick={() => remove(item)} className="border border-red-300 px-3 py-1.5 text-sm text-red-700">Delete</button></div></div>)}{!messages.length && <p className="p-5 text-slate">No portal messages.</p>}</div></div>
}
