import { useEffect, useState } from 'react'
import PortalLayout from '../components/PortalLayout'
import { useAuth } from '../lib/AuthContext'
import { supabase } from '../lib/supabaseClient'

export default function UserDashboard() {
  const { user } = useAuth()
  const [tab, setTab] = useState('documents')
  const [docs, setDocs] = useState([]), [personal, setPersonal] = useState([]), [enquiries, setEnquiries] = useState([])
  const [form, setForm] = useState({ subject: '', message: '', priority: 'normal' })
  const [loading, setLoading] = useState(true), [sending, setSending] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  useEffect(() => { load() }, [user?.id])
  async function load() { if (!user?.id) return; setLoading(true); setError(''); const [a, b, c] = await Promise.all([supabase.from('documents').select('id,title,category,file_path,created_at').order('created_at', { ascending: false }), supabase.from('portal_messages').select('id,subject,message,priority,is_read,created_at').eq('sender_id', user.id).is('archived_at', null).order('created_at', { ascending: false }), supabase.from('contact_messages').select('id,name,phone,email,message,created_at').order('created_at', { ascending: false })]); setDocs(a.data || []); setPersonal(b.data || []); setEnquiries(c.data || []); setError(a.error?.message || b.error?.message || c.error?.message || ''); setLoading(false) }
  async function download(doc) { const { data, error: e } = await supabase.storage.from('documents').createSignedUrl(doc.file_path, 60); if (e || !data?.signedUrl) setError(e?.message || 'Unable to create download link.'); else window.open(data.signedUrl, '_blank', 'noopener,noreferrer') }
  async function send(event) { event.preventDefault(); setSending(true); setError(''); const { error: e } = await supabase.from('portal_messages').insert({ sender_id: user.id, ...form }); setSending(false); if (e) setError(e.message); else { setForm({ subject: '', message: '', priority: 'normal' }); setSuccess('Message sent to Admin.'); load() } }
  const tabs = [['documents','Documents'], ['messages','Message Admin'], ['enquiries','Customer Enquiries']]
  return <PortalLayout><h1 className="mb-1 text-3xl font-display">My Portal</h1><p className="mb-6 text-sm text-slate">View documents, messages and customer enquiries.</p><div className="mb-6 flex flex-wrap gap-1 border-b border-slate/20">{tabs.map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`border-b-2 px-4 py-2.5 text-sm ${tab === id ? 'border-rust text-rust' : 'border-transparent text-slate'}`}>{label}</button>)}</div>{error && <p className="mb-4 text-sm text-rust">{error}</p>}{success && <p className="mb-4 text-sm text-green-700">{success}</p>}{loading ? <p className="text-slate">Loading…</p> : <>{tab === 'documents' && <div className="divide-y divide-slate/20 border border-slate/20 bg-white/40">{docs.map((doc) => <div key={doc.id} className="flex items-center justify-between p-4"><div><strong>{doc.title}</strong><p className="text-xs text-slate">{doc.category}</p></div><button onClick={() => download(doc)} className="border border-rust px-3 py-1.5 text-sm text-rust">Download</button></div>)}{!docs.length && <p className="p-5 text-slate">No documents available.</p>}</div>}{tab === 'messages' && <div className="grid gap-8 lg:grid-cols-3"><form onSubmit={send} className="h-fit space-y-4 border border-slate/20 p-5"><h2 className="font-display text-xl">Message Admin</h2><input required placeholder="Subject" value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} className="w-full border p-2" /><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} className="w-full border p-2"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><textarea required rows={5} placeholder="Message" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} className="w-full border p-2" /><button disabled={sending} className="w-full bg-rust py-2 text-sand">{sending ? 'Sending…' : 'Send Message'}</button></form><div className="lg:col-span-2"><h2 className="mb-3 font-display text-xl">My Messages</h2><MessageList items={personal} /></div></div>}{tab === 'enquiries' && <div><h2 className="mb-3 font-display text-xl">Customer Enquiries</h2><p className="mb-4 text-sm text-slate">Shared enquiries submitted from the public Get In Touch form.</p><div className="divide-y divide-slate/20 border border-slate/20 bg-white/40">{enquiries.map((item) => <div key={item.id} className="p-5"><div className="flex justify-between gap-3"><strong>{item.name}</strong><span className="text-xs text-slate">{new Date(item.created_at).toLocaleString()}</span></div><p className="text-xs text-slate">{item.phone || 'No phone'} · {item.email || 'No email'}</p><p className="mt-2 text-sm">{item.message}</p></div>)}{!enquiries.length && <p className="p-5 text-slate">No enquiries yet.</p>}</div></div>}</>}</PortalLayout>
}
function MessageList({ items }) { return <div className="divide-y divide-slate/20 border border-slate/20 bg-white/40">{items.map((item) => <div key={item.id} className="p-4"><strong>{item.subject}</strong><p className="text-sm text-slate">{item.message}</p><p className="mt-2 text-xs text-slate">{item.priority} · {item.is_read ? 'Read' : 'Unread'}</p></div>)}{!items.length && <p className="p-5 text-slate">No messages yet.</p>}</div> }
